dist: trusty
language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_token:
    secure: sGWXoHFNGw3hhxMPntT3Njk9ZJuDSpWtTF9m66bqD2YF2SHMM3lHYVPiKOQFVbb9+aMuV8yzGMHEBoC9naVOeTZ6CgDgAp6K3dCIavn9pfy5kSmAlAS1gkxt6sBuc/0InPNAr/T63+eH5mzQjER8lxuaq/4zp91+u1GoqYDEgsRF63i0nry8VlSrcJqyH7gziwV12DVvu4KQ5xRRIVdSXRadZ+Ht7VuEIf0TBgDABugQew7OiytRWNVCSEQGuwS9tvTVkyr3AvlmWxjS5M2SmE9XamHIAcBV7/gMF2QGzO20No+4xov363uyCWExHUyztehD6jI3QGP+vgQk/boafiVqoEBiKGgBS2dAknPaN8hZhKBSR4J87WvecG61CMyXsuASk6TlYfPbWH7VZrop4XajOqhnlrWz2qlbo3l8Gkdkijk7j4GNj8yXunIn7ABfWyi6NGDkc3yaSjJg0TKtFZxeS+C46l5zhexLstre91fa1RrvKiJ56efTaO86m5LSOsNPTtBWlA+QUNfVMQ18vIDzVk/KwXM8isCMqwD6rSRe6uQmebIBEKxc7/IEaYaHdUhBafGpbTxOwNwEte6ZAMuNooiP4u8Uoci0pT5MUmrr0g4Y44jatwLvuLVYxbXXGlyMZQQ7LDxpDswknY1gomiCHk8r90zk4zioa0Dhbkk=
  on:
    tags: true
