version: '2'

services:
  web:
    build: .
    working_dir: /var/www/SpaceInvasion
    command:
      psql --host=db -c "CREATE ROLE space_invasion WITH SUPERUSER LOGIN ENCRYPTED PASSWORD 'space_invasion_admin_pass';" &&
      psql --host=db -c "CREATE DATABASE space_invasion_db DEFAULT CHARSET 'utf8';" &&
      psql --host=db -c "GRANT ALL ON DATABASE space_invasion_db TO space_invasion;" &&
      java -jar ./SpaceInvasion-1.0.0-SNAPSHOT.jar
    depends_on:
    - db
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/SpaceInvasion
    restart: always

  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./postgres:/var/lib/postgresql
    - ./log/postgres:/var/log/postgresql
    - ./ets/postgres:/etc/postgresql
    restart: always
